# Generated by Django 4.0.4 on 2022-06-08 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_closet_outer_category1'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet_onepiece',
            name='closet_onepiece_fit',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
