# Generated by Django 4.0.4 on 2022-06-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_closet_onepiece_closet_onepiece_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet_onepiece',
            name='category1',
            field=models.TextField(choices=[('1', 'type1'), ('1', 'type2'), ('1', 'type3')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closet_pants',
            name='category1',
            field=models.TextField(choices=[('1', 'type1'), ('1', 'type2'), ('1', 'type3')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='closet_top',
            name='category1',
            field=models.TextField(choices=[('1', 'type1'), ('1', 'type2'), ('1', 'type3')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='closet_outer',
            name='category1',
            field=models.TextField(choices=[('1', 'type1'), ('1', 'type2'), ('1', 'type3')], default='', max_length=20),
        ),
    ]
