# Generated by Django 4.0.4 on 2022-05-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220527_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closet',
            old_name='content',
            new_name='closet_content',
        ),
        migrations.RenameField(
            model_name='closet',
            old_name='create_date',
            new_name='closet_create_date',
        ),
        migrations.RenameField(
            model_name='closet',
            old_name='subject',
            new_name='closet_title',
        ),
        migrations.RenameField(
            model_name='closet',
            old_name='mainphoto',
            new_name='closet_uploadedFile',
        ),
    ]
