# Generated by Django 4.0.4 on 2022-05-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_content_closet_closet_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='closet_create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
