# Generated by Django 4.0.4 on 2022-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_closet_closet_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='closet_url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
