# Generated by Django 4.0.4 on 2022-06-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_closet_category1_closet_category2_closet_category3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='closet_content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
