# Generated by Django 4.0.4 on 2022-06-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_closet_closet_content_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='category1',
            field=models.CharField(choices=[('1', '1'), ('1', '1'), ('1', '1')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='closet',
            name='category2',
            field=models.CharField(choices=[('1', '1'), ('1', '1'), ('1', '1')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='closet',
            name='category3',
            field=models.CharField(choices=[('1', '1'), ('1', '1'), ('1', '1')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='closet',
            name='category4',
            field=models.CharField(choices=[('1', '1'), ('1', '1'), ('1', '1')], default='', max_length=20),
        ),
    ]
