# Generated by Django 4.0.4 on 2022-06-07 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_alter_closet_category1_alter_closet_category2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='auth_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='closet',
            name='category1',
            field=models.TextField(choices=[('1', '1'), ('1', '1'), ('1', '1')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='closet',
            name='category2',
            field=models.TextField(choices=[('1', '1'), ('1', '1'), ('1', '1')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='closet',
            name='category3',
            field=models.TextField(choices=[('1', '1'), ('1', '1'), ('1', '1')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='closet',
            name='category4',
            field=models.TextField(choices=[('1', '1'), ('1', '1'), ('1', '1')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Closet_top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closet_top_title', models.CharField(max_length=200)),
                ('Closet_top_url', models.CharField(max_length=50, null=True)),
                ('closet_top_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category1', models.BooleanField(default=True)),
                ('category2', models.BooleanField(default=True)),
                ('category3', models.BooleanField(default=True)),
                ('category4', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Closet_pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closet_pants_title', models.CharField(max_length=200)),
                ('Closet_pants_url', models.CharField(max_length=50, null=True)),
                ('closet_pants_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category1', models.BooleanField(default=True)),
                ('category2', models.BooleanField(default=True)),
                ('category3', models.BooleanField(default=True)),
                ('category4', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Closet_outer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closet_outer_title', models.CharField(max_length=200)),
                ('Closet_outer_url', models.CharField(max_length=50, null=True)),
                ('closet_outer_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category1', models.BooleanField(default=True)),
                ('category2', models.BooleanField(default=True)),
                ('category3', models.BooleanField(default=True)),
                ('category4', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Closet_onepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closet_onepiece_title', models.CharField(max_length=200)),
                ('Closet_onepiece_url', models.CharField(max_length=50, null=True)),
                ('closet_onepiece_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category1', models.BooleanField(default=True)),
                ('category2', models.BooleanField(default=True)),
                ('category3', models.BooleanField(default=True)),
                ('category4', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
