# Generated by Django 4.0.4 on 2022-06-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_closet_auth_user_alter_closet_category1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closet_onepiece',
            old_name='Closet_onepiece_title',
            new_name='closet_onepiece_title',
        ),
        migrations.RenameField(
            model_name='closet_onepiece',
            old_name='Closet_onepiece_url',
            new_name='closet_onepiece_url',
        ),
        migrations.RenameField(
            model_name='closet_outer',
            old_name='Closet_outer_title',
            new_name='closet_outer_title',
        ),
        migrations.RenameField(
            model_name='closet_outer',
            old_name='Closet_outer_url',
            new_name='closet_outer_url',
        ),
        migrations.RenameField(
            model_name='closet_pants',
            old_name='Closet_pants_title',
            new_name='closet_pants_title',
        ),
        migrations.RenameField(
            model_name='closet_pants',
            old_name='Closet_pants_url',
            new_name='closet_pants_url',
        ),
        migrations.RenameField(
            model_name='closet_top',
            old_name='Closet_top_title',
            new_name='closet_top_title',
        ),
        migrations.RenameField(
            model_name='closet_top',
            old_name='Closet_top_url',
            new_name='closet_top_url',
        ),
    ]
