# Generated by Django 4.0.4 on 2022-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_closet_onepiece_title_closet_onepiece_closet_onepiece_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet_onepiece',
            name='closet_onepiece_uploadedFile',
            field=models.ImageField(blank=True, null=True, upload_to='images/closet_onepiece'),
        ),
        migrations.AlterField(
            model_name='closet_outer',
            name='closet_outer_uploadedFile',
            field=models.ImageField(blank=True, null=True, upload_to='images/closet_outer'),
        ),
        migrations.AlterField(
            model_name='closet_pants',
            name='closet_pants_uploadedFile',
            field=models.ImageField(blank=True, null=True, upload_to='images/closet_pants'),
        ),
        migrations.AlterField(
            model_name='closet_top',
            name='closet_top_uploadedFile',
            field=models.ImageField(blank=True, null=True, upload_to='images/closet_top'),
        ),
    ]
